# Generated by Django 5.1.4 on 2025-03-14 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GarminWatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("image", models.URLField()),
                ("fitness_tracking", models.BooleanField(default=False)),
                ("gps", models.BooleanField(default=False)),
                ("touchscreen", models.BooleanField(default=False)),
                ("notifications", models.BooleanField(default=False)),
                ("swimming", models.BooleanField(default=False)),
                ("cycling", models.BooleanField(default=False)),
                ("running", models.BooleanField(default=False)),
                ("hiking", models.BooleanField(default=False)),
                ("rugged", models.BooleanField(default=False)),
                ("battery_life", models.IntegerField()),
            ],
        ),
    ]
